version: 1
disable_existing_loggers: True

formatters:
  default:
    format: '[%(asctime)s]: [ %(module)-10s ] #%(levelname)-6s: %(name)-20s -  %(message)s'

  detail_info:
    format: '[%(asctime)s]: [ %(module)-10s ][ (func name: %(funcName)-15s line %(lineno)-4d) ] #%(levelname)-6s: %(name)-20s -  %(message)s'


filters:
  critical_filter:
    (): clients.logger.filters.CriticalLogFilter

  error_filter:
    (): clients.logger.filters.ErrorLogFilter

  warning_filter:
    (): clients.logger.filters.WarningLogFilter

  debug_info_filter:
    (): clients.logger.filters.DebugInfoLogFilter


handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  stderr:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr

  stdout:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  debug_info_file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/debug_info.log
    formatter: default
    mode: a
    maxBytes: 5000000
    backupCount: 2
    filters: [debug_info_filter]

  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: detail_info
    filename: logs/error.log
    mode: a
    maxBytes: 5000000
    backupCount: 2
    filters: [error_filter]

  critical_file:
    class: logging.handlers.RotatingFileHandler
    formatter: detail_info
    filename: logs/critical.log
    mode: a
    maxBytes: 5000000
    backupCount: 2
    filters: [critical_filter]


loggers:
  __main__:
    level: INFO
    handlers: [stderr, error_file, critical_file]

  aiogram.dispatcher:
    level: 'INFO'
    handlers: [debug_info_file, error_file, critical_file]

  aiogram.event:
    level: 'INFO'
    handlers: [debug_info_file, error_file, critical_file]

  aiogram.middlewares:
    level: 'INFO'
    handlers: [debug_info_file, error_file, critical_file]

  aiogram.webhook:
    level: 'INFO'
    handlers: [debug_info_file, error_file, critical_file]

  aiogram.scene:
    level: 'INFO'
    handlers: [debug_info_file, error_file, critical_file]

root:
  level: DEBUG
  formatter: default
  handlers: [stderr, debug_info_file, error_file, critical_file]