"""Create table 'UserSettings'

Revision ID: 50aea4ced593
Revises: 090ba3dc16d1
Create Date: 2025-04-27 10:18:31.393995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50aea4ced593'
down_revision: Union[str, None] = '090ba3dc16d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language_locale', postgresql.ENUM('ru', 'en', name='language_locales'), nullable=True),
    sa.Column('dialog_type', postgresql.ENUM('default_state', 'aiogram_dialog', name='dialog_types'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
