"""Add column title for File model

Revision ID: 6e70d01cd7c4
Revises: e01c2e649769
Create Date: 2025-04-05 11:03:20.166740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e70d01cd7c4'
down_revision: Union[str, None] = 'e01c2e649769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('title', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'files', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'title')
    # ### end Alembic commands ###
