"""Add column 'Type' for model File

Revision ID: c28ecdc6f6a8
Revises: b7c9b7c6a131
Create Date: 2025-04-05 13:18:13.783719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c28ecdc6f6a8'
down_revision: Union[str, None] = '6e70d01cd7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    object_type = sa.Enum('voice', 'video', 'video_note', 'document', 'photo', 'text', "undefined", name='objecttype')
    object_type.create(op.get_bind(), checkfirst=True)
    op.add_column('files', sa.Column('type', object_type, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'type')
    # ### end Alembic commands ###
